/**
 * Unit tests for microReticulum Resource receive-side support
 *
 * Tests ResourceAdvertisement parsing, Resource::accept(),
 * part reception, hashmap management, assembly, hash verification,
 * and proof generation using known Python-generated test vectors.
 */

#include <unity.h>
#include "Bytes.h"
#include "Link.h"
#include "Resource.h"
#include "ResourceData.h"
#include "Identity.h"
#include "Type.h"
#include "Cryptography/Hashes.h"

#ifdef RET_BZ2_SUPPORT
#include "bz2/bzlib.h"
#endif

#include <ArduinoJson.h>
#include <cmath>

using namespace RNS;

void setUp(void) {}
void tearDown(void) {}

// ============================================================
// Test vectors generated by Python RNS (umsgpack)
// ============================================================

// Original data: "Hello from Python resource!" (27 bytes)
static const uint8_t original_data[] = {
    0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x66, 0x72,
    0x6F, 0x6D, 0x20, 0x50, 0x79, 0x74, 0x68, 0x6F,
    0x6E, 0x20, 0x72, 0x65, 0x73, 0x6F, 0x75, 0x72,
    0x63, 0x65, 0x21
};
static const size_t original_data_len = 27;

// Nonce (prepended to data to form transfer payload)
static const uint8_t nonce[] = {0xCA, 0xFE, 0xBA, 0xBE};

// Random hash used for resource hashing
static const uint8_t random_hash_bytes[] = {0xDE, 0xAD, 0xBE, 0xEF};

// Transfer data = nonce + original_data (31 bytes)
static const uint8_t transfer_data[] = {
    0xCA, 0xFE, 0xBA, 0xBE,
    0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x66, 0x72,
    0x6F, 0x6D, 0x20, 0x50, 0x79, 0x74, 0x68, 0x6F,
    0x6E, 0x20, 0x72, 0x65, 0x73, 0x6F, 0x75, 0x72,
    0x63, 0x65, 0x21
};
static const size_t transfer_data_len = 31;

// Resource hash = SHA256(original_data + random_hash)
static const uint8_t resource_hash_bytes[] = {
    0x46, 0x3E, 0x17, 0xA8, 0x40, 0xF9, 0xBC, 0x3D,
    0x08, 0x18, 0x07, 0xD1, 0xEC, 0xE8, 0xAF, 0xBB,
    0x2E, 0xF6, 0x53, 0x33, 0x4B, 0xC8, 0x9C, 0x72,
    0x69, 0xBE, 0xED, 0xAD, 0x17, 0x8C, 0x7B, 0x52
};

// Expected proof = SHA256(original_data + resource_hash)
static const uint8_t expected_proof_bytes[] = {
    0x75, 0xA7, 0x40, 0x48, 0xA9, 0x59, 0x02, 0x61,
    0x4A, 0xBE, 0xFE, 0xA5, 0xE3, 0x73, 0x07, 0x24,
    0x4D, 0xDB, 0x28, 0x7F, 0x4A, 0x18, 0x8E, 0xA8,
    0x4A, 0xAD, 0xDF, 0x36, 0x93, 0xD1, 0x6B, 0xDD
};

// Map hash for part 0 = SHA256(transfer_data + random_hash)[:4]
static const uint8_t map_hash_part0[] = {0x20, 0xC5, 0x6F, 0xC8};

// Packed ResourceAdvertisement from Python umsgpack (110 bytes)
static const uint8_t packed_advertisement[] = {
    0x8B, 0xA1, 0x74, 0x1F, 0xA1, 0x64, 0x1B, 0xA1,
    0x6E, 0x01, 0xA1, 0x68, 0xC4, 0x20, 0x46, 0x3E,
    0x17, 0xA8, 0x40, 0xF9, 0xBC, 0x3D, 0x08, 0x18,
    0x07, 0xD1, 0xEC, 0xE8, 0xAF, 0xBB, 0x2E, 0xF6,
    0x53, 0x33, 0x4B, 0xC8, 0x9C, 0x72, 0x69, 0xBE,
    0xED, 0xAD, 0x17, 0x8C, 0x7B, 0x52, 0xA1, 0x72,
    0xC4, 0x04, 0xDE, 0xAD, 0xBE, 0xEF, 0xA1, 0x6F,
    0xC4, 0x20, 0x46, 0x3E, 0x17, 0xA8, 0x40, 0xF9,
    0xBC, 0x3D, 0x08, 0x18, 0x07, 0xD1, 0xEC, 0xE8,
    0xAF, 0xBB, 0x2E, 0xF6, 0x53, 0x33, 0x4B, 0xC8,
    0x9C, 0x72, 0x69, 0xBE, 0xED, 0xAD, 0x17, 0x8C,
    0x7B, 0x52, 0xA1, 0x69, 0x01, 0xA1, 0x6C, 0x01,
    0xA1, 0x71, 0xC0, 0xA1, 0x66, 0x00, 0xA1, 0x6D,
    0xC4, 0x04, 0x20, 0xC5, 0x6F, 0xC8
};
static const size_t packed_advertisement_len = 110;


// ============================================================
// ResourceAdvertisement::unpack tests
// ============================================================

void test_adv_unpack_basic_fields(void) {
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    TEST_ASSERT_EQUAL(31, adv.t);   // transfer size
    TEST_ASSERT_EQUAL(27, adv.d);   // data size
    TEST_ASSERT_EQUAL(1, adv.n);    // num parts
    TEST_ASSERT_EQUAL(1, adv.i);    // segment index
    TEST_ASSERT_EQUAL(1, adv.l);    // total segments
    TEST_ASSERT_EQUAL(0x00, adv.f); // flags
}

void test_adv_unpack_hash_fields(void) {
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    Bytes expected_hash(resource_hash_bytes, 32);
    Bytes expected_random(random_hash_bytes, 4);
    Bytes expected_map(map_hash_part0, 4);

    TEST_ASSERT_EQUAL(32, adv.h.size());
    TEST_ASSERT_TRUE(adv.h == expected_hash);

    TEST_ASSERT_EQUAL(4, adv.r.size());
    TEST_ASSERT_TRUE(adv.r == expected_random);

    TEST_ASSERT_EQUAL(32, adv.o.size());
    TEST_ASSERT_TRUE(adv.o == expected_hash); // original_hash == hash for single segment

    TEST_ASSERT_EQUAL(4, adv.m.size());
    TEST_ASSERT_TRUE(adv.m == expected_map);
}

void test_adv_unpack_flags_all_clear(void) {
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    TEST_ASSERT_FALSE(adv.e);  // not encrypted
    TEST_ASSERT_FALSE(adv.c);  // not compressed
    TEST_ASSERT_FALSE(adv.s);  // not split
    TEST_ASSERT_FALSE(adv.u);  // not request
    TEST_ASSERT_FALSE(adv.p);  // not response
    TEST_ASSERT_FALSE(adv.x);  // no metadata
}

void test_adv_unpack_null_request_id(void) {
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    // request_id is null in our test vector
    TEST_ASSERT_FALSE(adv.q);
}

void test_adv_unpack_flags_decoding(void) {
    // Build a custom advertisement with flags = 0x13 (encrypted + compressed + is_response)
    // f = 0x13 = 0b00010011 → e=1, c=1, s=0, u=0, p=1
    JsonDocument doc;
    doc["t"] = 100;
    doc["d"] = 80;
    doc["n"] = 1;
    doc["h"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["r"] = MsgPackBinary(random_hash_bytes, 4);
    doc["o"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["i"] = 1;
    doc["l"] = 1;
    doc["q"] = MsgPackBinary(random_hash_bytes, 4); // non-null request_id
    doc["f"] = 0x13;
    doc["m"] = MsgPackBinary(map_hash_part0, 4);

    uint8_t buffer[256];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));
    Bytes packed(buffer, len);

    ResourceAdvertisement adv = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_TRUE(adv.e);   // bit 0
    TEST_ASSERT_TRUE(adv.c);   // bit 1
    TEST_ASSERT_FALSE(adv.s);  // bit 2
    TEST_ASSERT_FALSE(adv.u);  // bit 3
    TEST_ASSERT_TRUE(adv.p);   // bit 4
    TEST_ASSERT_FALSE(adv.x);  // bit 5
    TEST_ASSERT_EQUAL(0x13, adv.f);

    // request_id should be set
    TEST_ASSERT_TRUE(adv.q);
    TEST_ASSERT_EQUAL(4, adv.q.size());
}

void test_adv_unpack_invalid_data_returns_defaults(void) {
    // ArduinoJson's deserializeMsgPack is lenient — many byte sequences parse
    // without error. Rather than relying on exceptions, verify that a garbage
    // advertisement has zero-valued fields (no valid resource hash, etc.)
    uint8_t garbage[] = {0xC1};  // msgpack "never used" type → parse error
    Bytes garbage_bytes(garbage, 1);
    bool threw = false;
    try {
        ResourceAdvertisement adv = ResourceAdvertisement::unpack(garbage_bytes);
    } catch (std::exception& e) {
        threw = true;
    }
    TEST_ASSERT_TRUE(threw);
}


// ============================================================
// Hash computation tests (cross-compatibility with Python)
// ============================================================

void test_resource_hash_matches_python(void) {
    // resource_hash = SHA256(original_data + random_hash)
    Bytes data(original_data, original_data_len);
    Bytes rh(random_hash_bytes, 4);

    Bytes hash_input;
    hash_input.append(data);
    hash_input.append(rh);

    Bytes computed = Identity::full_hash(hash_input);
    Bytes expected(resource_hash_bytes, 32);

    TEST_ASSERT_EQUAL(32, computed.size());
    TEST_ASSERT_TRUE(computed == expected);
}

void test_map_hash_matches_python(void) {
    // map_hash = SHA256(transfer_data + random_hash)[:4]
    Bytes td(transfer_data, transfer_data_len);
    Bytes rh(random_hash_bytes, 4);

    Bytes hash_input;
    hash_input.append(td);
    hash_input.append(rh);

    Bytes full = Identity::full_hash(hash_input);
    Bytes computed = full.left(Type::Resource::MAPHASH_LEN);
    Bytes expected(map_hash_part0, 4);

    TEST_ASSERT_EQUAL(4, computed.size());
    TEST_ASSERT_TRUE(computed == expected);
}

void test_proof_hash_matches_python(void) {
    // proof = SHA256(original_data + resource_hash)
    Bytes data(original_data, original_data_len);
    Bytes hash(resource_hash_bytes, 32);

    Bytes proof_input;
    proof_input.append(data);
    proof_input.append(hash);

    Bytes computed = Identity::full_hash(proof_input);
    Bytes expected(expected_proof_bytes, 32);

    TEST_ASSERT_EQUAL(32, computed.size());
    TEST_ASSERT_TRUE(computed == expected);
}


// ============================================================
// Resource state machine tests (using ResourceData directly)
// ============================================================

// Helper: build a ResourceAdvertisement with custom parameters, pack it
static Bytes build_test_advertisement(
    size_t transfer_size, size_t data_size, uint16_t num_parts,
    const Bytes& hash, const Bytes& random_hash, const Bytes& hashmap,
    uint8_t flags = 0x00
) {
    JsonDocument doc;
    doc["t"] = transfer_size;
    doc["d"] = data_size;
    doc["n"] = num_parts;
    doc["h"] = MsgPackBinary(hash.data(), hash.size());
    doc["r"] = MsgPackBinary(random_hash.data(), random_hash.size());
    doc["o"] = MsgPackBinary(hash.data(), hash.size());
    doc["i"] = 1;
    doc["l"] = 1;
    doc["q"] = nullptr;
    doc["f"] = flags;
    doc["m"] = MsgPackBinary(hashmap.data(), hashmap.size());

    uint8_t buffer[512];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));
    return Bytes(buffer, len);
}

void test_adv_unpack_roundtrip(void) {
    Bytes hash(resource_hash_bytes, 32);
    Bytes rh(random_hash_bytes, 4);
    Bytes hm(map_hash_part0, 4);

    Bytes packed = build_test_advertisement(31, 27, 1, hash, rh, hm);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_EQUAL(31, adv.t);
    TEST_ASSERT_EQUAL(27, adv.d);
    TEST_ASSERT_EQUAL(1, adv.n);
    TEST_ASSERT_TRUE(adv.h == hash);
    TEST_ASSERT_TRUE(adv.r == rh);
    TEST_ASSERT_TRUE(adv.m == hm);
}


// ============================================================
// Resource progress calculation
// ============================================================

void test_progress_none_resource(void) {
    Resource r(Type::NONE);
    // NONE resource should not crash on get_progress, but it will assert
    // Just verify the bool operator
    TEST_ASSERT_FALSE(r);
}


// ============================================================
// is_request / is_response static helpers
// ============================================================

void test_adv_is_request(void) {
    // Build advertisement with is_request flag set (bit 3) and request_id present
    // flags = 0x08 (is_request)
    JsonDocument doc;
    doc["t"] = 100;
    doc["d"] = 80;
    doc["n"] = 1;
    doc["h"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["r"] = MsgPackBinary(random_hash_bytes, 4);
    doc["o"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["i"] = 1;
    doc["l"] = 1;
    uint8_t req_id[] = {0x01, 0x02, 0x03, 0x04};
    doc["q"] = MsgPackBinary(req_id, 4);
    doc["f"] = 0x08;  // is_request bit
    doc["m"] = MsgPackBinary(map_hash_part0, 4);

    uint8_t buffer[256];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));
    Bytes packed(buffer, len);

    ResourceAdvertisement adv = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_TRUE(adv.u);   // is_request
    TEST_ASSERT_FALSE(adv.p);  // not is_response
    TEST_ASSERT_TRUE(adv.q);   // has request_id
}

void test_adv_is_response(void) {
    // flags = 0x10 (is_response)
    JsonDocument doc;
    doc["t"] = 100;
    doc["d"] = 80;
    doc["n"] = 1;
    doc["h"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["r"] = MsgPackBinary(random_hash_bytes, 4);
    doc["o"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["i"] = 1;
    doc["l"] = 1;
    uint8_t req_id[] = {0x01, 0x02, 0x03, 0x04};
    doc["q"] = MsgPackBinary(req_id, 4);
    doc["f"] = 0x10;  // is_response bit
    doc["m"] = MsgPackBinary(map_hash_part0, 4);

    uint8_t buffer[256];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));
    Bytes packed(buffer, len);

    ResourceAdvertisement adv = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_FALSE(adv.u);  // not is_request
    TEST_ASSERT_TRUE(adv.p);   // is_response
}


// ============================================================
// Multi-part hashmap management
// ============================================================

void test_hashmap_update_populates_entries(void) {
    // Build a 3-part hashmap and verify entries are stored correctly
    uint8_t hm_data[] = {
        0x11, 0x22, 0x33, 0x44,  // part 0
        0x55, 0x66, 0x77, 0x88,  // part 1
        0xAA, 0xBB, 0xCC, 0xDD,  // part 2
    };
    Bytes hashmap(hm_data, sizeof(hm_data));

    Bytes part0_expected(hm_data, 4);
    Bytes part1_expected(hm_data + 4, 4);
    Bytes part2_expected(hm_data + 8, 4);

    // We can't directly call hashmap_update without a Resource object,
    // but we can verify the hash computation that feeds into it
    TEST_ASSERT_EQUAL(12, hashmap.size());
    TEST_ASSERT_EQUAL(3, hashmap.size() / Type::Resource::MAPHASH_LEN);

    // Verify we can extract individual hashes
    Bytes h0 = hashmap.mid(0 * Type::Resource::MAPHASH_LEN, Type::Resource::MAPHASH_LEN);
    Bytes h1 = hashmap.mid(1 * Type::Resource::MAPHASH_LEN, Type::Resource::MAPHASH_LEN);
    Bytes h2 = hashmap.mid(2 * Type::Resource::MAPHASH_LEN, Type::Resource::MAPHASH_LEN);

    TEST_ASSERT_TRUE(h0 == part0_expected);
    TEST_ASSERT_TRUE(h1 == part1_expected);
    TEST_ASSERT_TRUE(h2 == part2_expected);
}


// ============================================================
// Assembly hash verification logic
// ============================================================

void test_assembly_hash_verification_logic(void) {
    // Simulate the assembly verification:
    // 1. Concatenate parts (for single part: just the transfer_data)
    // 2. Strip nonce (first RANDOM_HASH_SIZE bytes)
    // 3. Verify SHA256(stripped_data + random_hash) == resource_hash

    Bytes stream(transfer_data, transfer_data_len);

    // Strip nonce
    Bytes data = stream.mid(Type::Resource::RANDOM_HASH_SIZE);
    TEST_ASSERT_EQUAL(original_data_len, data.size());

    // Verify the stripped data matches original
    Bytes expected_data(original_data, original_data_len);
    TEST_ASSERT_TRUE(data == expected_data);

    // Verify hash
    Bytes hash_input;
    hash_input.append(data);
    hash_input.append(Bytes(random_hash_bytes, 4));
    Bytes calculated_hash = Identity::full_hash(hash_input);

    Bytes expected_hash(resource_hash_bytes, 32);
    TEST_ASSERT_TRUE(calculated_hash == expected_hash);
}

void test_assembly_hash_verification_fails_on_corruption(void) {
    // Flip a byte in the transfer data
    uint8_t corrupted[transfer_data_len];
    memcpy(corrupted, transfer_data, transfer_data_len);
    corrupted[10] ^= 0xFF;  // corrupt a byte

    Bytes stream(corrupted, transfer_data_len);
    Bytes data = stream.mid(Type::Resource::RANDOM_HASH_SIZE);

    Bytes hash_input;
    hash_input.append(data);
    hash_input.append(Bytes(random_hash_bytes, 4));
    Bytes calculated_hash = Identity::full_hash(hash_input);

    Bytes expected_hash(resource_hash_bytes, 32);
    TEST_ASSERT_FALSE(calculated_hash == expected_hash);
}


// ============================================================
// Proof generation logic
// ============================================================

void test_proof_generation_logic(void) {
    // proof = SHA256(assembled_data + resource_hash)
    Bytes data(original_data, original_data_len);
    Bytes hash(resource_hash_bytes, 32);

    Bytes proof_input;
    proof_input.append(data);
    proof_input.append(hash);
    Bytes proof = Identity::full_hash(proof_input);

    // proof_packet_data = resource_hash + proof
    Bytes proof_data;
    proof_data.append(hash);
    proof_data.append(proof);

    TEST_ASSERT_EQUAL(64, proof_data.size());

    // First 32 bytes should be resource hash
    TEST_ASSERT_TRUE(proof_data.left(32) == hash);

    // Last 32 bytes should be the proof
    Bytes expected_proof(expected_proof_bytes, 32);
    TEST_ASSERT_TRUE(proof_data.mid(32) == expected_proof);
}


// ============================================================
// Request-next packet format
// ============================================================

void test_request_packet_format_not_exhausted(void) {
    // Request packet: [0x00][resource_hash (32 bytes)][part_hashes...]
    // When hashmap is NOT exhausted, first byte is 0x00
    Bytes request_data;
    request_data.append((uint8_t)Type::Resource::HASHMAP_IS_NOT_EXHAUSTED);
    request_data.append(Bytes(resource_hash_bytes, 32));
    request_data.append(Bytes(map_hash_part0, 4));

    TEST_ASSERT_EQUAL(37, request_data.size());
    TEST_ASSERT_EQUAL(0x00, request_data.data()[0]);
    // resource hash starts at byte 1
    TEST_ASSERT_TRUE(request_data.mid(1, 32) == Bytes(resource_hash_bytes, 32));
    // part hash at byte 33
    TEST_ASSERT_TRUE(request_data.mid(33, 4) == Bytes(map_hash_part0, 4));
}

void test_request_packet_format_exhausted(void) {
    // When hashmap IS exhausted:
    // [0xFF][last_map_hash (4 bytes)][resource_hash (32 bytes)][part_hashes...]
    Bytes request_data;
    request_data.append((uint8_t)Type::Resource::HASHMAP_IS_EXHAUSTED);
    request_data.append(Bytes(map_hash_part0, 4));  // last known hash
    request_data.append(Bytes(resource_hash_bytes, 32));

    TEST_ASSERT_EQUAL(37, request_data.size());
    TEST_ASSERT_EQUAL(0xFF, request_data.data()[0]);
    // last map hash at byte 1
    TEST_ASSERT_TRUE(request_data.mid(1, 4) == Bytes(map_hash_part0, 4));
    // resource hash at byte 5
    TEST_ASSERT_TRUE(request_data.mid(5, 32) == Bytes(resource_hash_bytes, 32));
}


// ============================================================
// SDU and part count calculations
// ============================================================

void test_sdu_constant(void) {
    // SDU should equal Packet::MDU
    TEST_ASSERT_EQUAL(Type::Packet::MDU, Type::Resource::SDU);
    TEST_ASSERT_TRUE(Type::Resource::SDU > 0);
}

void test_part_count_single_part(void) {
    // 31 bytes with SDU of ~464 = 1 part
    uint16_t total_parts = (uint16_t)std::ceil(31.0f / (float)Type::Resource::SDU);
    TEST_ASSERT_EQUAL(1, total_parts);
}

void test_part_count_multi_part(void) {
    // 2000 bytes with SDU of 464 = ceil(2000/464) = 5 parts
    uint16_t total_parts = (uint16_t)std::ceil(2000.0f / (float)Type::Resource::SDU);
    TEST_ASSERT_EQUAL(5, total_parts);
}

void test_part_count_exact_boundary(void) {
    // Exactly SDU bytes = 1 part (not 2)
    uint16_t total_parts = (uint16_t)std::ceil((float)Type::Resource::SDU / (float)Type::Resource::SDU);
    TEST_ASSERT_EQUAL(1, total_parts);
}


// ============================================================
// Type constants sanity
// ============================================================

void test_resource_constants(void) {
    TEST_ASSERT_EQUAL(4, Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_EQUAL(4, Type::Resource::WINDOW);
    TEST_ASSERT_EQUAL(4, Type::Resource::RANDOM_HASH_SIZE);
    TEST_ASSERT_EQUAL(8, Type::Resource::MAX_RETRIES);
    TEST_ASSERT_EQUAL(0x00, Type::Resource::HASHMAP_IS_NOT_EXHAUSTED);
    TEST_ASSERT_EQUAL(0xFF, Type::Resource::HASHMAP_IS_EXHAUSTED);
    TEST_ASSERT_TRUE(Type::Resource::ResourceAdvertisement::HASHMAP_MAX_LEN > 0);
}

void test_resource_status_values(void) {
    TEST_ASSERT_EQUAL(0x00, Type::Resource::NONE);
    TEST_ASSERT_EQUAL(0x03, Type::Resource::TRANSFERRING);
    TEST_ASSERT_EQUAL(0x05, Type::Resource::ASSEMBLING);
    TEST_ASSERT_EQUAL(0x06, Type::Resource::COMPLETE);
    TEST_ASSERT_EQUAL(0x07, Type::Resource::FAILED);
    TEST_ASSERT_EQUAL(0x08, Type::Resource::CORRUPT);
}


// ============================================================
// Cross-compatibility: Python-packed advertisement parsed by C++
// ============================================================

void test_python_advertisement_parsed_correctly(void) {
    // This is the key cross-compatibility test: a real Python-packed
    // advertisement must be correctly parsed by C++
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    // Verify all fields match what Python packed
    TEST_ASSERT_EQUAL(31, adv.t);
    TEST_ASSERT_EQUAL(27, adv.d);
    TEST_ASSERT_EQUAL(1, adv.n);
    TEST_ASSERT_EQUAL(0x00, adv.f);
    TEST_ASSERT_EQUAL(1, adv.i);
    TEST_ASSERT_EQUAL(1, adv.l);
    TEST_ASSERT_FALSE(adv.q); // null request_id

    // Hash fields
    TEST_ASSERT_TRUE(adv.h == Bytes(resource_hash_bytes, 32));
    TEST_ASSERT_TRUE(adv.r == Bytes(random_hash_bytes, 4));
    TEST_ASSERT_TRUE(adv.o == Bytes(resource_hash_bytes, 32));
    TEST_ASSERT_TRUE(adv.m == Bytes(map_hash_part0, 4));

    // And the map hash we'd compute for the transfer data matches
    // what Python put in the advertisement hashmap
    Bytes td(transfer_data, transfer_data_len);
    Bytes rh(random_hash_bytes, 4);
    Bytes hash_input;
    hash_input.append(td);
    hash_input.append(rh);
    Bytes computed_map_hash = Identity::full_hash(hash_input).left(Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_TRUE(computed_map_hash == adv.m);
}


// ============================================================
// End-to-end assembly simulation (no link/packet needed)
// ============================================================

void test_end_to_end_assembly_simulation(void) {
    // Simulate the full receive flow without a real Link:
    // 1. Parse advertisement
    // 2. Compute total_parts
    // 3. Match part against hashmap
    // 4. Assemble (concatenate, strip nonce, verify hash)
    // 5. Compute proof

    // Step 1: Parse
    Bytes adv_data(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement adv = ResourceAdvertisement::unpack(adv_data);

    // Step 2: Compute parts
    uint16_t sdu = Type::Resource::SDU;
    uint16_t total_parts = (uint16_t)std::ceil((float)adv.t / (float)sdu);
    TEST_ASSERT_EQUAL(1, total_parts);

    // Step 3: Populate hashmap from advertisement
    std::vector<Bytes> hashmap(total_parts);
    uint16_t hashes = adv.m.size() / Type::Resource::MAPHASH_LEN;
    for (uint16_t i = 0; i < hashes && i < total_parts; i++) {
        hashmap[i] = adv.m.mid(i * Type::Resource::MAPHASH_LEN, Type::Resource::MAPHASH_LEN);
    }
    TEST_ASSERT_TRUE(hashmap[0]);

    // Step 4: "Receive" the part and match it
    Bytes part_data(transfer_data, transfer_data_len);

    // Compute map hash for received part
    Bytes map_hash_input;
    map_hash_input.append(part_data);
    map_hash_input.append(adv.r);
    Bytes computed_map_hash = Identity::full_hash(map_hash_input).left(Type::Resource::MAPHASH_LEN);

    // Should match hashmap[0]
    TEST_ASSERT_TRUE(computed_map_hash == hashmap[0]);

    // Step 5: Assemble
    Bytes stream = part_data;  // single part
    Bytes assembled = stream.mid(Type::Resource::RANDOM_HASH_SIZE);
    TEST_ASSERT_EQUAL(27, assembled.size());

    // Verify hash
    Bytes verify_input;
    verify_input.append(assembled);
    verify_input.append(adv.r);
    Bytes calculated_hash = Identity::full_hash(verify_input);
    TEST_ASSERT_TRUE(calculated_hash == adv.h);

    // Step 6: Compute proof
    Bytes proof_input;
    proof_input.append(assembled);
    proof_input.append(adv.h);
    Bytes proof = Identity::full_hash(proof_input);
    TEST_ASSERT_TRUE(proof == Bytes(expected_proof_bytes, 32));
}


// ============================================================
// Send-side: ResourceAdvertisement::pack() tests
// ============================================================

void test_adv_pack_unpack_roundtrip(void) {
    // Build an advertisement, pack it, unpack it, verify all fields match
    ResourceAdvertisement adv;
    adv.t = 31;
    adv.d = 27;
    adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x00;
    adv.i = 1;
    adv.l = 1;
    adv.q = Bytes();  // null
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);
    TEST_ASSERT_TRUE(packed.size() > 0);

    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);
    TEST_ASSERT_EQUAL(adv.t, unpacked.t);
    TEST_ASSERT_EQUAL(adv.d, unpacked.d);
    TEST_ASSERT_EQUAL(adv.n, unpacked.n);
    TEST_ASSERT_TRUE(adv.h == unpacked.h);
    TEST_ASSERT_TRUE(adv.r == unpacked.r);
    TEST_ASSERT_TRUE(adv.o == unpacked.o);
    TEST_ASSERT_EQUAL(adv.f, unpacked.f);
    TEST_ASSERT_EQUAL(adv.i, unpacked.i);
    TEST_ASSERT_EQUAL(adv.l, unpacked.l);
    TEST_ASSERT_TRUE(adv.m == unpacked.m);
}

void test_adv_pack_with_flags(void) {
    // Pack with various flags set and verify roundtrip
    ResourceAdvertisement adv;
    adv.t = 500;
    adv.d = 400;
    adv.n = 2;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x13;  // encrypted + compressed + is_response
    adv.i = 1;
    adv.l = 1;
    uint8_t req_id[] = {0x01, 0x02, 0x03, 0x04};
    adv.q = Bytes(req_id, 4);
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_EQUAL(0x13, unpacked.f);
    TEST_ASSERT_TRUE(unpacked.e);   // encrypted
    TEST_ASSERT_TRUE(unpacked.c);   // compressed
    TEST_ASSERT_TRUE(unpacked.p);   // is_response
    TEST_ASSERT_FALSE(unpacked.u);  // not is_request
    TEST_ASSERT_EQUAL(500, unpacked.t);
    TEST_ASSERT_EQUAL(400, unpacked.d);
    TEST_ASSERT_EQUAL(2, unpacked.n);
    TEST_ASSERT_TRUE(unpacked.q);
    TEST_ASSERT_EQUAL(4, unpacked.q.size());
}

void test_adv_pack_cross_compat_with_python(void) {
    // Pack the same advertisement that Python produced, verify it unpacks identically
    // This tests that our pack produces data compatible with our unpack
    ResourceAdvertisement adv;
    adv.t = 31;
    adv.d = 27;
    adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x00;
    adv.i = 1;
    adv.l = 1;
    adv.q = Bytes();  // null
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);

    // The Python-packed version should also unpack identically
    Bytes python_packed(packed_advertisement, packed_advertisement_len);
    ResourceAdvertisement from_python = ResourceAdvertisement::unpack(python_packed);
    ResourceAdvertisement from_cpp = ResourceAdvertisement::unpack(packed);

    // Both should produce identical fields
    TEST_ASSERT_EQUAL(from_python.t, from_cpp.t);
    TEST_ASSERT_EQUAL(from_python.d, from_cpp.d);
    TEST_ASSERT_EQUAL(from_python.n, from_cpp.n);
    TEST_ASSERT_TRUE(from_python.h == from_cpp.h);
    TEST_ASSERT_TRUE(from_python.r == from_cpp.r);
    TEST_ASSERT_TRUE(from_python.o == from_cpp.o);
    TEST_ASSERT_TRUE(from_python.m == from_cpp.m);
    TEST_ASSERT_EQUAL(from_python.f, from_cpp.f);
    TEST_ASSERT_EQUAL(from_python.i, from_cpp.i);
    TEST_ASSERT_EQUAL(from_python.l, from_cpp.l);
}

void test_adv_pack_multipart_hashmap(void) {
    // Pack with multiple hashmap entries
    uint8_t hm_data[] = {
        0x11, 0x22, 0x33, 0x44,
        0x55, 0x66, 0x77, 0x88,
        0xAA, 0xBB, 0xCC, 0xDD,
    };
    ResourceAdvertisement adv;
    adv.t = 1500;
    adv.d = 1200;
    adv.n = 3;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x01;  // encrypted
    adv.i = 1;
    adv.l = 1;
    adv.q = Bytes();
    adv.m = Bytes(hm_data, sizeof(hm_data));

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_EQUAL(3, unpacked.n);
    TEST_ASSERT_EQUAL(12, unpacked.m.size());  // 3 * 4 bytes
    TEST_ASSERT_TRUE(unpacked.m == Bytes(hm_data, sizeof(hm_data)));
}


// ============================================================
// Send-side: proof validation tests
// ============================================================

void test_validate_proof_logic_correct(void) {
    // Simulate proof validation: expected_proof == SHA256(data + hash)
    Bytes data(original_data, original_data_len);
    Bytes hash(resource_hash_bytes, 32);
    Bytes expected(expected_proof_bytes, 32);

    // Compute expected proof
    Bytes proof_input;
    proof_input.append(data);
    proof_input.append(hash);
    Bytes computed = Identity::full_hash(proof_input);

    TEST_ASSERT_TRUE(computed == expected);

    // Simulate proof packet: resource_hash + proof
    Bytes proof_data;
    proof_data.append(hash);
    proof_data.append(computed);

    // Validate: extract and compare
    Bytes received_hash = proof_data.left(32);
    Bytes received_proof = proof_data.mid(32);
    TEST_ASSERT_TRUE(received_hash == hash);
    TEST_ASSERT_TRUE(received_proof == expected);
}

void test_validate_proof_logic_incorrect(void) {
    // Bad proof should not match
    Bytes hash(resource_hash_bytes, 32);
    Bytes expected(expected_proof_bytes, 32);

    // Corrupt the proof
    uint8_t bad_proof[32];
    memcpy(bad_proof, expected_proof_bytes, 32);
    bad_proof[0] ^= 0xFF;
    Bytes bad(bad_proof, 32);

    TEST_ASSERT_FALSE(bad == expected);
}


// ============================================================
// Send-side: request parsing logic tests
// ============================================================

void test_request_parsing_not_exhausted(void) {
    // Simulate parsing a RESOURCE_REQ (not exhausted) as the sender would
    // Format: [0x00][resource_hash (32)][part_hash_0 (4)][part_hash_1 (4)]...

    Bytes req;
    req.append((uint8_t)Type::Resource::HASHMAP_IS_NOT_EXHAUSTED);
    req.append(Bytes(resource_hash_bytes, 32));
    req.append(Bytes(map_hash_part0, 4));

    // Parse
    bool exhausted = req.data()[0] == Type::Resource::HASHMAP_IS_EXHAUSTED;
    TEST_ASSERT_FALSE(exhausted);

    size_t offset = 1;
    size_t hash_len = Type::Identity::HASHLENGTH / 8;
    Bytes res_hash = req.mid(offset, hash_len);
    offset += hash_len;
    TEST_ASSERT_TRUE(res_hash == Bytes(resource_hash_bytes, 32));

    // Extract requested part hashes
    uint16_t num_requested = (uint16_t)((req.size() - offset) / Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_EQUAL(1, num_requested);

    Bytes part_hash = req.mid(offset, Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_TRUE(part_hash == Bytes(map_hash_part0, 4));
}

void test_request_parsing_exhausted(void) {
    // Simulate parsing a RESOURCE_REQ (exhausted)
    // Format: [0xFF][last_map_hash (4)][resource_hash (32)][part_hashes...]

    Bytes req;
    req.append((uint8_t)Type::Resource::HASHMAP_IS_EXHAUSTED);
    req.append(Bytes(map_hash_part0, 4));  // last known hash
    req.append(Bytes(resource_hash_bytes, 32));

    bool exhausted = req.data()[0] == Type::Resource::HASHMAP_IS_EXHAUSTED;
    TEST_ASSERT_TRUE(exhausted);

    size_t offset = 1;
    Bytes last_hash = req.mid(offset, Type::Resource::MAPHASH_LEN);
    offset += Type::Resource::MAPHASH_LEN;
    TEST_ASSERT_TRUE(last_hash == Bytes(map_hash_part0, 4));

    size_t hash_len = Type::Identity::HASHLENGTH / 8;
    Bytes res_hash = req.mid(offset, hash_len);
    offset += hash_len;
    TEST_ASSERT_TRUE(res_hash == Bytes(resource_hash_bytes, 32));

    // No additional part hashes in this example
    uint16_t num_requested = (uint16_t)((req.size() - offset) / Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_EQUAL(0, num_requested);
}


// ============================================================
// Send-side: splitting logic tests
// ============================================================

void test_send_split_calculation(void) {
    // Verify that data larger than SDU would result in correct number of parts
    size_t sdu = Type::Resource::SDU;
    size_t data_size = sdu * 3 + 100;  // 3 full parts + 1 partial
    uint16_t expected_parts = (uint16_t)std::ceil((float)data_size / (float)sdu);
    TEST_ASSERT_EQUAL(4, expected_parts);

    // Verify each part size
    size_t remaining = data_size;
    for (uint16_t i = 0; i < expected_parts; i++) {
        size_t chunk = std::min((size_t)sdu, remaining);
        if (i < expected_parts - 1) {
            TEST_ASSERT_EQUAL(sdu, chunk);
        } else {
            TEST_ASSERT_EQUAL(100, chunk);
        }
        remaining -= chunk;
    }
    TEST_ASSERT_EQUAL(0, remaining);
}

void test_send_hashmap_no_collision(void) {
    // Generate distinct part data, verify no hashmap collisions
    Bytes random_hash(random_hash_bytes, 4);
    std::set<Bytes> seen;
    bool collision = false;

    for (int i = 0; i < 10; i++) {
        // Create distinct part data
        uint8_t part[8] = {(uint8_t)i, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
        Bytes part_data(part, sizeof(part));

        Bytes hash_input;
        hash_input.append(part_data);
        hash_input.append(random_hash);
        Bytes mh = Identity::full_hash(hash_input).left(Type::Resource::MAPHASH_LEN);

        if (seen.count(mh) > 0) {
            collision = true;
            break;
        }
        seen.insert(mh);
    }
    TEST_ASSERT_FALSE(collision);
}


// ============================================================
// Send-side: flags byte encoding
// ============================================================

void test_flags_byte_encoding_encrypted(void) {
    // Encrypted flag only: 0x01
    uint8_t flags = 0;
    flags |= 0x01; // encrypted
    TEST_ASSERT_EQUAL(0x01, flags);

    // Roundtrip through pack/unpack
    ResourceAdvertisement adv;
    adv.t = 100; adv.d = 80; adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x01; adv.i = 1; adv.l = 1;
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);
    TEST_ASSERT_TRUE(unpacked.e);   // encrypted
    TEST_ASSERT_FALSE(unpacked.c);  // not compressed
    TEST_ASSERT_FALSE(unpacked.s);  // not split
    TEST_ASSERT_FALSE(unpacked.u);  // not request
    TEST_ASSERT_FALSE(unpacked.p);  // not response
}

void test_flags_byte_encoding_all_bits(void) {
    // All relevant bits set: 0x3F = 0b00111111
    ResourceAdvertisement adv;
    adv.t = 100; adv.d = 80; adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x3F; adv.i = 1; adv.l = 1;
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);
    TEST_ASSERT_TRUE(unpacked.e);   // bit 0
    TEST_ASSERT_TRUE(unpacked.c);   // bit 1
    TEST_ASSERT_TRUE(unpacked.s);   // bit 2
    TEST_ASSERT_TRUE(unpacked.u);   // bit 3
    TEST_ASSERT_TRUE(unpacked.p);   // bit 4
    TEST_ASSERT_TRUE(unpacked.x);   // bit 5
    TEST_ASSERT_EQUAL(0x3F, unpacked.f);
}

void test_flags_byte_is_request_encoding(void) {
    // is_request flag = 0x08, with encrypted = 0x01 → 0x09
    uint8_t flags = 0;
    flags |= 0x01; // encrypted
    flags |= 0x08; // is_request
    TEST_ASSERT_EQUAL(0x09, flags);

    ResourceAdvertisement adv;
    adv.t = 100; adv.d = 80; adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = flags; adv.i = 1; adv.l = 1;
    uint8_t req_id[] = {0xAA, 0xBB, 0xCC, 0xDD};
    adv.q = Bytes(req_id, 4);
    adv.m = Bytes(map_hash_part0, 4);

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);
    TEST_ASSERT_TRUE(unpacked.e);   // encrypted
    TEST_ASSERT_TRUE(unpacked.u);   // is_request
    TEST_ASSERT_FALSE(unpacked.p);  // not is_response
    TEST_ASSERT_TRUE(unpacked.q);   // has request_id
}


// ============================================================
// Send-side: large advertisement pack
// ============================================================

void test_adv_pack_large_hashmap(void) {
    // Pack an advertisement with many hashmap entries (simulating a large resource)
    const uint16_t num_parts = 20;
    uint8_t hm_data[num_parts * 4];
    for (uint16_t i = 0; i < num_parts; i++) {
        hm_data[i*4 + 0] = (uint8_t)(i >> 8);
        hm_data[i*4 + 1] = (uint8_t)(i & 0xFF);
        hm_data[i*4 + 2] = 0xAA;
        hm_data[i*4 + 3] = 0xBB;
    }

    ResourceAdvertisement adv;
    adv.t = num_parts * Type::Resource::SDU;
    adv.d = num_parts * Type::Resource::SDU - 100;
    adv.n = num_parts;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x01; adv.i = 1; adv.l = 1;
    adv.m = Bytes(hm_data, sizeof(hm_data));

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_EQUAL(num_parts, unpacked.n);
    TEST_ASSERT_EQUAL(sizeof(hm_data), unpacked.m.size());
    TEST_ASSERT_TRUE(unpacked.m == Bytes(hm_data, sizeof(hm_data)));
}

void test_adv_pack_empty_hashmap(void) {
    // Edge case: advertisement with no hashmap data (shouldn't happen normally
    // but pack/unpack should handle gracefully)
    ResourceAdvertisement adv;
    adv.t = 100; adv.d = 80; adv.n = 1;
    adv.h = Bytes(resource_hash_bytes, 32);
    adv.r = Bytes(random_hash_bytes, 4);
    adv.o = Bytes(resource_hash_bytes, 32);
    adv.f = 0x01; adv.i = 1; adv.l = 1;
    adv.m = Bytes();  // empty

    Bytes packed = ResourceAdvertisement::pack(adv);
    ResourceAdvertisement unpacked = ResourceAdvertisement::unpack(packed);

    TEST_ASSERT_EQUAL(1, unpacked.n);
    TEST_ASSERT_EQUAL(0, unpacked.m.size());
}


// ============================================================
// Send-side: multi-segment request parsing
// ============================================================

void test_request_parsing_multiple_parts(void) {
    // Request for 3 parts at once
    uint8_t hash0[] = {0x11, 0x22, 0x33, 0x44};
    uint8_t hash1[] = {0x55, 0x66, 0x77, 0x88};
    uint8_t hash2[] = {0xAA, 0xBB, 0xCC, 0xDD};

    Bytes req;
    req.append((uint8_t)Type::Resource::HASHMAP_IS_NOT_EXHAUSTED);
    req.append(Bytes(resource_hash_bytes, 32));
    req.append(Bytes(hash0, 4));
    req.append(Bytes(hash1, 4));
    req.append(Bytes(hash2, 4));

    // Parse
    size_t offset = 1;
    size_t hash_len = Type::Identity::HASHLENGTH / 8;
    offset += hash_len;  // skip resource hash

    uint16_t num_requested = (uint16_t)((req.size() - offset) / Type::Resource::MAPHASH_LEN);
    TEST_ASSERT_EQUAL(3, num_requested);

    // Verify each part hash
    Bytes h0 = req.mid(offset, 4); offset += 4;
    Bytes h1 = req.mid(offset, 4); offset += 4;
    Bytes h2 = req.mid(offset, 4); offset += 4;
    TEST_ASSERT_TRUE(h0 == Bytes(hash0, 4));
    TEST_ASSERT_TRUE(h1 == Bytes(hash1, 4));
    TEST_ASSERT_TRUE(h2 == Bytes(hash2, 4));
}


// ============================================================
// Send-side: HMU packet format verification
// ============================================================

void test_hmu_packet_format(void) {
    // Verify the HMU packet format: resource_hash + msgpack([segment, hashmap_bytes])
    uint8_t hm_data[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88};
    uint16_t segment = 1;

    JsonDocument doc;
    doc.add(segment);
    doc.add(MsgPackBinary(hm_data, sizeof(hm_data)));

    uint8_t packed_buf[128];
    size_t packed_len = serializeMsgPack(doc, packed_buf, sizeof(packed_buf));

    Bytes hmu_data;
    hmu_data.append(Bytes(resource_hash_bytes, 32));
    hmu_data.append(Bytes(packed_buf, packed_len));

    // Verify: first 32 bytes are resource hash
    TEST_ASSERT_TRUE(hmu_data.left(32) == Bytes(resource_hash_bytes, 32));

    // Remaining bytes are msgpack
    Bytes packed = hmu_data.mid(32);
    JsonDocument unpacked;
    DeserializationError error = deserializeMsgPack(unpacked, packed.data(), packed.size());
    TEST_ASSERT_FALSE(error);
    TEST_ASSERT_TRUE(unpacked.is<JsonArray>());
    TEST_ASSERT_EQUAL(segment, unpacked[0].as<uint16_t>());
    MsgPackBinary bin = unpacked[1].as<MsgPackBinary>();
    TEST_ASSERT_EQUAL(sizeof(hm_data), bin.size());
}


// ============================================================
// Send-side: proof packet format
// ============================================================

void test_proof_packet_full_format(void) {
    // Verify the complete proof packet format and validation logic
    Bytes data(original_data, original_data_len);
    Bytes hash(resource_hash_bytes, 32);

    // Sender computes expected proof
    Bytes proof_input;
    proof_input.append(data);
    proof_input.append(hash);
    Bytes expected_proof = Identity::full_hash(proof_input);

    // Receiver computes actual proof (same formula)
    Bytes receiver_proof_input;
    receiver_proof_input.append(data);
    receiver_proof_input.append(hash);
    Bytes actual_proof = Identity::full_hash(receiver_proof_input);

    // Receiver sends: resource_hash + proof
    Bytes proof_packet;
    proof_packet.append(hash);
    proof_packet.append(actual_proof);

    // Sender validates
    Bytes received_hash = proof_packet.left(32);
    Bytes received_proof = proof_packet.mid(32);

    TEST_ASSERT_TRUE(received_hash == hash);
    TEST_ASSERT_TRUE(received_proof == expected_proof);
    TEST_ASSERT_EQUAL(64, proof_packet.size());
}


// ============================================================
// Bug fix: zero parts guard
// ============================================================

void test_zero_parts_advertisement_rejected(void) {
    // Advertisement with n=0 should be rejected
    Bytes hash(resource_hash_bytes, 32);
    Bytes rh(random_hash_bytes, 4);
    Bytes hm(map_hash_part0, 4);

    // Build advertisement with n=0
    JsonDocument doc;
    doc["t"] = 0;
    doc["d"] = 0;
    doc["n"] = 0;
    doc["h"] = MsgPackBinary(hash.data(), hash.size());
    doc["r"] = MsgPackBinary(rh.data(), rh.size());
    doc["o"] = MsgPackBinary(hash.data(), hash.size());
    doc["i"] = 1;
    doc["l"] = 1;
    doc["q"] = nullptr;
    doc["f"] = 0;
    doc["m"] = MsgPackBinary(hm.data(), hm.size());

    uint8_t buffer[256];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));

    ResourceAdvertisement adv = ResourceAdvertisement::unpack(Bytes(buffer, len));
    // Verify the fields that would trigger rejection in accept()
    TEST_ASSERT_EQUAL(0, adv.t);
    TEST_ASSERT_EQUAL(0, adv.n);
}


// ============================================================
// bz2 decompression tests (guarded by RET_BZ2_SUPPORT)
// ============================================================

#ifdef RET_BZ2_SUPPORT

// Test vector generated by Python: bz2.compress(b"Hello from Reticulum Resource! " * 10)
// Original: 310 bytes -> Compressed: 84 bytes
static const size_t bz2_test_original_len = 310;
static const size_t bz2_test_compressed_len = 84;
static const uint8_t bz2_test_compressed[] = {
    0x42, 0x5a, 0x68, 0x39, 0x31, 0x41, 0x59, 0x26, 0x53, 0x59, 0x0b, 0x80,
    0x9f, 0x07, 0x00, 0x00, 0x1d, 0x97, 0x80, 0x60, 0x00, 0x00, 0x40, 0x10,
    0x00, 0x0b, 0x26, 0x9e, 0x00, 0x20, 0x00, 0x6a, 0x0a, 0x55, 0x00, 0x68,
    0x00, 0xa5, 0x50, 0x00, 0x34, 0xc9, 0x30, 0x4e, 0x93, 0x84, 0xd5, 0x57,
    0x69, 0xd2, 0x61, 0x39, 0x4c, 0x13, 0x64, 0xf5, 0x38, 0x4f, 0x53, 0x04,
    0xed, 0x33, 0x4e, 0xd3, 0x09, 0xaa, 0x61, 0x37, 0x27, 0x89, 0xba, 0x70,
    0x9f, 0x8b, 0xb9, 0x22, 0x9c, 0x28, 0x48, 0x05, 0xc0, 0x4f, 0x83, 0x80,
};

static const char bz2_test_original_str[] = "Hello from Reticulum Resource! "
    "Hello from Reticulum Resource! " "Hello from Reticulum Resource! "
    "Hello from Reticulum Resource! " "Hello from Reticulum Resource! "
    "Hello from Reticulum Resource! " "Hello from Reticulum Resource! "
    "Hello from Reticulum Resource! " "Hello from Reticulum Resource! "
    "Hello from Reticulum Resource! ";

void test_bz2_decompress_basic(void) {
    unsigned int dest_len = bz2_test_original_len + 1024;
    uint8_t* dest = (uint8_t*)malloc(dest_len);
    TEST_ASSERT_NOT_NULL(dest);

    int ret = BZ2_bzBuffToBuffDecompress(
        (char*)dest, &dest_len,
        (char*)bz2_test_compressed, (unsigned int)bz2_test_compressed_len,
        0, 0);

    TEST_ASSERT_EQUAL(BZ_OK, ret);
    TEST_ASSERT_EQUAL(bz2_test_original_len, dest_len);
    TEST_ASSERT_EQUAL_MEMORY(bz2_test_original_str, dest, bz2_test_original_len);

    free(dest);
}

void test_bz2_decompress_corrupt_data(void) {
    // Corrupt the compressed data and verify graceful failure
    uint8_t garbage[] = {0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x11, 0x22, 0x33};
    unsigned int dest_len = 4096;
    uint8_t* dest = (uint8_t*)malloc(dest_len);
    TEST_ASSERT_NOT_NULL(dest);

    int ret = BZ2_bzBuffToBuffDecompress(
        (char*)dest, &dest_len,
        (char*)garbage, sizeof(garbage),
        0, 0);

    // Should return an error, not crash
    TEST_ASSERT_NOT_EQUAL(BZ_OK, ret);

    free(dest);
}

void test_bz2_decompress_empty_input(void) {
    unsigned int dest_len = 1024;
    uint8_t* dest = (uint8_t*)malloc(dest_len);
    TEST_ASSERT_NOT_NULL(dest);

    // Empty input should fail gracefully
    int ret = BZ2_bzBuffToBuffDecompress(
        (char*)dest, &dest_len,
        (char*)"", 0,
        0, 0);

    TEST_ASSERT_NOT_EQUAL(BZ_OK, ret);

    free(dest);
}

void test_compressed_advertisement_accepted(void) {
    // Build advertisement with compressed flag set (bit 1)
    // flags = 0x03 (encrypted + compressed)
    JsonDocument doc;
    doc["t"] = 100;
    doc["d"] = 200;  // decompressed size > transfer size
    doc["n"] = 1;
    doc["h"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["r"] = MsgPackBinary(random_hash_bytes, 4);
    doc["o"] = MsgPackBinary(resource_hash_bytes, 32);
    doc["i"] = 1;
    doc["l"] = 1;
    doc["q"] = nullptr;
    doc["f"] = 0x03;  // encrypted + compressed
    doc["m"] = MsgPackBinary(map_hash_part0, 4);

    uint8_t buffer[256];
    size_t len = serializeMsgPack(doc, buffer, sizeof(buffer));
    Bytes packed(buffer, len);

    ResourceAdvertisement adv = ResourceAdvertisement::unpack(packed);
    TEST_ASSERT_TRUE(adv.c);   // compressed flag is set
    TEST_ASSERT_TRUE(adv.e);   // encrypted flag is set

    // With RET_BZ2_SUPPORT defined, the compressed flag should NOT cause
    // Resource::accept() to reject the advertisement. We can't call accept()
    // directly (needs a real Packet/Link), but we verify the flag is preserved
    // through pack/unpack, which is what accept() reads.
    TEST_ASSERT_EQUAL(0x03, adv.f);
    TEST_ASSERT_EQUAL(200, adv.d);  // decompressed total_size
    TEST_ASSERT_EQUAL(100, adv.t);  // compressed transfer size
}

#endif // RET_BZ2_SUPPORT


int main(int argc, char **argv) {
    UNITY_BEGIN();

    // ResourceAdvertisement parsing
    RUN_TEST(test_adv_unpack_basic_fields);
    RUN_TEST(test_adv_unpack_hash_fields);
    RUN_TEST(test_adv_unpack_flags_all_clear);
    RUN_TEST(test_adv_unpack_null_request_id);
    RUN_TEST(test_adv_unpack_flags_decoding);
    RUN_TEST(test_adv_unpack_invalid_data_returns_defaults);
    RUN_TEST(test_adv_unpack_roundtrip);
    RUN_TEST(test_adv_is_request);
    RUN_TEST(test_adv_is_response);

    // Hash computations (cross-compat with Python)
    RUN_TEST(test_resource_hash_matches_python);
    RUN_TEST(test_map_hash_matches_python);
    RUN_TEST(test_proof_hash_matches_python);

    // Assembly logic
    RUN_TEST(test_assembly_hash_verification_logic);
    RUN_TEST(test_assembly_hash_verification_fails_on_corruption);
    RUN_TEST(test_proof_generation_logic);

    // Hashmap management
    RUN_TEST(test_hashmap_update_populates_entries);

    // Request packet format
    RUN_TEST(test_request_packet_format_not_exhausted);
    RUN_TEST(test_request_packet_format_exhausted);

    // Part count calculations
    RUN_TEST(test_sdu_constant);
    RUN_TEST(test_part_count_single_part);
    RUN_TEST(test_part_count_multi_part);
    RUN_TEST(test_part_count_exact_boundary);

    // Type constants
    RUN_TEST(test_resource_constants);
    RUN_TEST(test_resource_status_values);

    // Cross-compatibility
    RUN_TEST(test_python_advertisement_parsed_correctly);

    // End-to-end simulation
    RUN_TEST(test_end_to_end_assembly_simulation);

    // Progress
    RUN_TEST(test_progress_none_resource);

    // --- Send-side tests ---

    // Pack/unpack roundtrip
    RUN_TEST(test_adv_pack_unpack_roundtrip);
    RUN_TEST(test_adv_pack_with_flags);
    RUN_TEST(test_adv_pack_cross_compat_with_python);
    RUN_TEST(test_adv_pack_multipart_hashmap);
    RUN_TEST(test_adv_pack_large_hashmap);
    RUN_TEST(test_adv_pack_empty_hashmap);

    // Flags encoding
    RUN_TEST(test_flags_byte_encoding_encrypted);
    RUN_TEST(test_flags_byte_encoding_all_bits);
    RUN_TEST(test_flags_byte_is_request_encoding);

    // Proof validation
    RUN_TEST(test_validate_proof_logic_correct);
    RUN_TEST(test_validate_proof_logic_incorrect);
    RUN_TEST(test_proof_packet_full_format);

    // Request parsing
    RUN_TEST(test_request_parsing_not_exhausted);
    RUN_TEST(test_request_parsing_exhausted);
    RUN_TEST(test_request_parsing_multiple_parts);

    // HMU format
    RUN_TEST(test_hmu_packet_format);

    // Splitting logic
    RUN_TEST(test_send_split_calculation);
    RUN_TEST(test_send_hashmap_no_collision);

    // Bug fix tests
    RUN_TEST(test_zero_parts_advertisement_rejected);

    // bz2 decompression tests
#ifdef RET_BZ2_SUPPORT
    RUN_TEST(test_bz2_decompress_basic);
    RUN_TEST(test_bz2_decompress_corrupt_data);
    RUN_TEST(test_bz2_decompress_empty_input);
    RUN_TEST(test_compressed_advertisement_accepted);
#endif

    return UNITY_END();
}
