"""Entry point for companion server."""

import argparse
import asyncio
import signal
import sys
import time
import logging
from pathlib import Path

from .config import Config
from .reticulum_service import ReticulumService
from .trust_manager import TrustManager


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Reticulum companion server for rDeck")
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run without TUI (for testing/daemon mode)",
    )
    parser.add_argument(
        "--tcp-port",
        type=int,
        help="TCP port for Reticulum TCP interface (generates config if needed)",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        help="Override data directory path",
    )
    parser.add_argument(
        "--with-maps",
        action="store_true",
        help="Enable maps service with default Docker URLs (tileserver=8081, valhalla=8002, nominatim=8080)",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging",
    )
    args = parser.parse_args()

    # Configure logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )

    # Load configuration
    if args.data_dir:
        config = Config(data_dir=Path(args.data_dir))
    else:
        config = Config()

    # Handle --with-maps: enable maps service with default Docker URLs
    if args.with_maps:
        config.maps_enabled = True
        if not config.maps_tileserver_url:
            config.maps_tileserver_url = "http://localhost:8081"
        if not config.maps_valhalla_url:
            config.maps_valhalla_url = "http://localhost:8002"
        if not config.maps_nominatim_url:
            config.maps_nominatim_url = "http://localhost:8080"
        if "maps" not in config.enabled_services:
            config.enabled_services.append("maps")
        config.save()

    # Handle --tcp-port: generate Reticulum config if needed
    if args.tcp_port:
        _ensure_reticulum_config(config.data_dir, args.tcp_port)

    # Initialize trust manager
    trust_manager = TrustManager(config.data_dir)

    # Initialize Reticulum service
    rns_service = ReticulumService(config, trust_manager)

    # Handle shutdown gracefully
    def shutdown_handler(signum, frame):
        rns_service.stop()
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown_handler)
    signal.signal(signal.SIGTERM, shutdown_handler)

    # Start Reticulum in background
    rns_service.start()

    if args.headless:
        # Headless mode: just run the service without TUI
        print(f"Companion server running in headless mode")
        print(f"Server name: {config.server_name}")
        print(f"Data directory: {config.data_dir}")
        print(f"Services: {', '.join(config.enabled_services)}")
        if rns_service.destination_hash:
            print(f"LXMF destination: {rns_service.destination_hash}")

        # Log callback for headless mode
        def log_handler(msg: str):
            print(f"[LOG] {msg}")

        rns_service.on_log(log_handler)

        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            pass
    else:
        # TUI mode
        from .tui.app import CompanionServerApp
        app = CompanionServerApp(rns_service, trust_manager)
        app.run()

    # Cleanup
    rns_service.stop()


def _ensure_reticulum_config(data_dir: Path, tcp_port: int):
    """Generate a Reticulum config with TCP server interface.

    Always writes the config when --tcp-port is specified, since an existing
    config may have been auto-generated by Reticulum without TCPServerInterface.

    Skipped if RNS_CONFIG_DIR is already set (explicit env var takes precedence).
    """
    import os

    if os.environ.get("RNS_CONFIG_DIR"):
        return

    rns_config_dir = data_dir / "reticulum"
    rns_config_dir.mkdir(parents=True, exist_ok=True)
    config_path = rns_config_dir / "config"

    # Check if existing config already has TCP on the right port
    needs_write = True
    if config_path.exists():
        content = config_path.read_text()
        if "TCPServerInterface" in content and f"listen_port = {tcp_port}" in content:
            needs_write = False

    if needs_write:
        logging.getLogger(__name__).info(
            f"Writing Reticulum config with TCP server on port {tcp_port}"
        )
        config_path.write_text(
            f"[reticulum]\n"
            f"  enable_transport = no\n"
            f"  share_instance = yes\n"
            f"  shared_instance_port = 37428\n"
            f"  instance_control_port = 37429\n"
            f"\n"
            f"[logging]\n"
            f"  loglevel = 4\n"
            f"\n"
            f"[interfaces]\n"
            f"  [[Default Interface]]\n"
            f"    type = AutoInterface\n"
            f"    interface_enabled = true\n"
            f"\n"
            f"  [[TCP Server]]\n"
            f"    type = TCPServerInterface\n"
            f"    interface_enabled = true\n"
            f"    listen_ip = 0.0.0.0\n"
            f"    listen_port = {tcp_port}\n"
        )

    os.environ["RNS_CONFIG_DIR"] = str(rns_config_dir)


if __name__ == "__main__":
    main()
