#include "timezones.h"

/* 
std::map<std::string,std::string> timezone_map{ 
{"Africa/Abidjan","GMT0"},
{"Africa/Accra","GMT0"},
{"Africa/Addis_Ababa","EAT-3"},
{"Africa/Algiers","CET-1"},
{"Africa/Asmara","EAT-3"},
{"Africa/Asmera","EAT-3"},
{"Africa/Bamako","GMT0"},
{"Africa/Bangui","WAT-1"},
{"Africa/Banjul","GMT0"},
{"Africa/Bissau","GMT0"},
{"Africa/Blantyre","CAT-2"},
{"Africa/Brazzaville","WAT-1"},
{"Africa/Bujumbura","CAT-2"},
{"Africa/Cairo","EET-2"},
{"Africa/Casablanca","WET0WEST,M3.5.0,M10.5.0/3"},
{"Africa/Ceuta","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Africa/Conakry","GMT0"},
{"Africa/Dakar","GMT0"},
{"Africa/Dar_es_Salaam","EAT-3"},
{"Africa/Djibouti","EAT-3"},
{"Africa/Douala","WAT-1"},
{"Africa/El_Aaiun","WET0WEST,M3.5.0,M10.5.0/3"},
{"Africa/Freetown","GMT0"},
{"Africa/Gaborone","CAT-2"},
{"Africa/Harare","CAT-2"},
{"Africa/Johannesburg","SAST-2"},
{"Africa/Juba","EAT-3"},
{"Africa/Kampala","EAT-3"},
{"Africa/Khartoum","EAT-3"},
{"Africa/Kigali","CAT-2"},
{"Africa/Kinshasa","WAT-1"},
{"Africa/Lagos","WAT-1"},
{"Africa/Libreville","WAT-1"},
{"Africa/Lome","GMT0"},
{"Africa/Luanda","WAT-1"},
{"Africa/Lubumbashi","CAT-2"},
{"Africa/Lusaka","CAT-2"},
{"Africa/Malabo","WAT-1"},
{"Africa/Maputo","CAT-2"},
{"Africa/Maseru","SAST-2"},
{"Africa/Mbabane","SAST-2"},
{"Africa/Mogadishu","EAT-3"},
{"Africa/Monrovia","GMT0"},
{"Africa/Nairobi","EAT-3"},
{"Africa/Ndjamena","WAT-1"},
{"Africa/Niamey","WAT-1"},
{"Africa/Nouakchott","GMT0"},
{"Africa/Ouagadougou","GMT0"},
{"Africa/Porto-Novo","WAT-1"},
{"Africa/Sao_Tome","GMT0"},
{"Africa/Timbuktu","GMT0"},
{"Africa/Tripoli","EET-2"},
{"Africa/Tunis","CET-1"},
{"Africa/Windhoek","WAT-1WAST,M9.1.0,M4.1.0"},
{"America/Adak","HST10HDT,M3.2.0,M11.1.0"},
{"America/Anchorage","AKST9AKDT,M3.2.0,M11.1.0"},
{"America/Anguilla","AST4"},
{"America/Antigua","AST4"},
{"America/Araguaina","BRT3"},
{"America/Argentina/Buenos_Aires","ART3"},
{"America/Argentina/Catamarca","ART3"},
{"America/Argentina/ComodRivadavia","ART3"},
{"America/Argentina/Cordoba","ART3"},
{"America/Argentina/Jujuy","ART3"},
{"America/Argentina/La_Rioja","ART3"},
{"America/Argentina/Mendoza","ART3"},
{"America/Argentina/Rio_Gallegos","ART3"},
{"America/Argentina/Salta","ART3"},
{"America/Argentina/San_Juan","ART3"},
{"America/Argentina/San_Luis","ART3"},
{"America/Argentina/Tucuman","ART3"},
{"America/Argentina/Ushuaia","ART3"},
{"America/Aruba","AST4"},
{"America/Asuncion","PYT4PYST,M10.1.0/0,M3.4.0/0"},
{"America/Atikokan","EST5"},
{"America/Atka","HST10HDT,M3.2.0,M11.1.0"},
{"America/Bahia","BRT3"},
{"America/Bahia_Banderas","CST6CDT,M4.1.0,M10.5.0"},
{"America/Barbados","AST4"},
{"America/Belem","BRT3"},
{"America/Belize","CST6"},
{"America/Blanc-Sablon","AST4"},
{"America/Boa_Vista","AMT4"},
{"America/Bogota","COT5"},
{"America/Boise","MST7MDT,M3.2.0,M11.1.0"},
{"America/Buenos_Aires","ART3"},
{"America/Cambridge_Bay","MST7MDT,M3.2.0,M11.1.0"},
{"America/Campo_Grande","AMT4AMST,M10.3.0/0,M2.3.0/0"},
{"America/Cancun","EST5"},
{"America/Caracas","VET4:30"},
{"America/Catamarca","ART3"},
{"America/Cayenne","GFT3"},
{"America/Cayman","EST5EDT,M3.2.0,M11.1.0"},
{"America/Chicago","CST6CDT,M3.2.0,M11.1.0"},
{"America/Chihuahua","MST7MDT,M4.1.0,M10.5.0"},
{"America/Ciudad_Juarez","MST7MDT,M3.2.0,M11.1.0"},
{"America/Coral_Harbour","EST5"},
{"America/Cordoba","ART3"},
{"America/Costa_Rica","CST6"},
{"America/Creston","MST7"},
{"America/Cuiaba","AMT4AMST,M10.3.0/0,M2.3.0/0"},
{"America/Curacao","AST4"},
{"America/Danmarkshavn","GMT0"},
{"America/Dawson","PST8PDT,M3.2.0,M11.1.0"},
{"America/Dawson_Creek","MST7"},
{"America/Denver","MST7MDT,M3.2.0,M11.1.0"},
{"America/Detroit","EST5EDT,M3.2.0,M11.1.0"},
{"America/Dominica","AST4"},
{"America/Edmonton","MST7MDT,M3.2.0,M11.1.0"},
{"America/Eirunepe","ACT5"},
{"America/El_Salvador","CST6"},
{"America/Ensenada","PST8PDT,M3.2.0,M11.1.0"},
{"America/Fortaleza","BRT3"},
{"America/Fort_Nelson","MST7"},
{"America/Fort_Wayne","EST5EDT,M3.2.0,M11.1.0"},
{"America/Glace_Bay","AST4ADT,M3.2.0,M11.1.0"},
{"America/Goose_Bay","AST4ADT,M3.2.0,M11.1.0"},
{"America/Grand_Turk","AST4"},
{"America/Grenada","AST4"},
{"America/Guadeloupe","AST4"},
{"America/Guatemala","CST6"},
{"America/Guayaquil","ECT5"},
{"America/Guyana","GYT4"},
{"America/Halifa","xAST4ADT,M3.2.0,M11.1.0"},
{"America/Havana","CST5CDT,M3.2.0/0,M11.1.0/1"},
{"America/Hermosillo","MST7"},
{"America/Indiana/Indianapolis","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indiana/Kno","xCST6CDT,M3.2.0,M11.1.0"},
{"America/Indiana/Marengo","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indiana/Petersburg","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indianapolis","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indiana/Tell_City","CST6CDT,M3.2.0,M11.1.0"},
{"America/Indiana/Vevay","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indiana/Vincennes","EST5EDT,M3.2.0,M11.1.0"},
{"America/Indiana/Winamac","EST5EDT,M3.2.0,M11.1.0"},
{"America/Inuvik","MST7MDT,M3.2.0,M11.1.0"},
{"America/Iqaluit","EST5EDT,M3.2.0,M11.1.0"},
{"America/Jamaica","EST5"},
{"America/Jujuy","ART3"},
{"America/Juneau","AKST9AKDT,M3.2.0,M11.1.0"},
{"America/Kentucky/Louisville","EST5EDT,M3.2.0,M11.1.0"},
{"America/Kentucky/Monticello","EST5EDT,M3.2.0,M11.1.0"},
{"America/Knox_IN","CST6CDT,M3.2.0,M11.1.0"},
{"America/Kralendijk","AST4"},
{"America/La_Paz","BOT4"},
{"America/Lima","PET5"},
{"America/Los_Angeles","PST8PDT,M3.2.0,M11.1.0"},
{"America/Louisville","EST5EDT,M3.2.0,M11.1.0"},
{"America/Lower_Princes","AST4"},
{"America/Maceio","BRT3"},
{"America/Managua","CST6"},
{"America/Manaus","AMT4"},
{"America/Marigot","AST4"},
{"America/Martinique","AST4"},
{"America/Matamoros","CST6CDT,M3.2.0,M11.1.0"},
{"America/Mazatlan","MST7MDT,M4.1.0,M10.5.0"},
{"America/Mendoza","ART3"},
{"America/Menominee","CST6CDT,M3.2.0,M11.1.0"},
{"America/Merida","CST6CDT,M4.1.0,M10.5.0"},
{"America/Metlakatla","PST8"},
{"America/Mexico_City","CST6CDT,M4.1.0,M10.5.0"},
{"America/Miquelon","PMST3PMDT,M3.2.0,M11.1.0"},
{"America/Moncton","AST4ADT,M3.2.0,M11.1.0"},
{"America/Monterrey","CST6CDT,M4.1.0,M10.5.0"},
{"America/Montevideo","UYT3"},
{"America/Montreal","EST5EDT,M3.2.0,M11.1.0"},
{"America/Montserrat","AST4"},
{"America/Nassau","EST5EDT,M3.2.0,M11.1.0"},
{"America/New_York","EST5EDT,M3.2.0,M11.1.0"},
{"America/Nipigon","EST5EDT,M3.2.0,M11.1.0"},
{"America/Nome","AKST9AKDT,M3.2.0,M11.1.0"},
{"America/Noronha","FNT2"},
{"America/North_Dakota/Beulah","CST6CDT,M3.2.0,M11.1.0"},
{"America/North_Dakota/Center","CST6CDT,M3.2.0,M11.1.0"},
{"America/North_Dakota/New_Salem","CST6CDT,M3.2.0,M11.1.0"},
{"America/Ojinaga","MST7MDT,M3.2.0,M11.1.0"},
{"America/Panama","EST5"},
{"America/Pangnirtung","EST5EDT,M3.2.0,M11.1.0"},
{"America/Paramaribo","SRT3"},
{"America/Phoeni","xMST7"},
{"America/Port-au-Prince","EST5EDT,M3.2.0,M11.1.0"},
{"America/Porto_Acre","ACT5"},
{"America/Port_of_Spain","AST4"},
{"America/Porto_Velho","AMT4"},
{"America/Puerto_Rico","AST4"},
{"America/Rainy_River","CST6CDT,M3.2.0,M11.1.0"},
{"America/Rankin_Inlet","CST6CDT,M3.2.0,M11.1.0"},
{"America/Recife","BRT3"},
{"America/Regina","CST6"},
{"America/Resolute","CST6CDT,M3.2.0,M11.1.0"},
{"America/Rio_Branco","ACT5"},
{"America/Rosario","ART3"},
{"America/Santa_Isabel","PST8PDT,M4.1.0,M10.5.0"},
{"America/Santarem","BRT3"},
{"America/Santiago","CLT3"},
{"America/Santo_Domingo","AST4"},
{"America/Sao_Paulo","BRT3BRST,M10.3.0/0,M2.3.0/0"},
{"America/Scoresbysund","EGT1EGST,M3.5.0/0,M10.5.0/1"},
{"America/Shiprock","MST7MDT,M3.2.0,M11.1.0"},
{"America/Sitka","AKST9AKDT,M3.2.0,M11.1.0"},
{"America/St_Barthelemy","AST4"},
{"America/St_Johns","NST3:30NDT,M3.2.0,M11.1.0"},
{"America/St_Kitts","AST4"},
{"America/St_Lucia","AST4"},
{"America/St_Thomas","AST4"},
{"America/St_Vincent","AST4"},
{"America/Swift_Current","CST6"},
{"America/Tegucigalpa","CST6"},
{"America/Thule","AST4ADT,M3.2.0,M11.1.0"},
{"America/Thunder_Bay","EST5EDT,M3.2.0,M11.1.0"},
{"America/Tijuana","PST8PDT,M3.2.0,M11.1.0"},
{"America/Toronto","EST5EDT,M3.2.0,M11.1.0"},
{"America/Tortola","AST4"},
{"America/Vancouver","PST8PDT,M3.2.0,M11.1.0"},
{"America/Virgin","AST4"},
{"America/Whitehorse","PST8PDT,M3.2.0,M11.1.0"},
{"America/Winnipeg","CST6CDT,M3.2.0,M11.1.0"},
{"America/Yakutat","AKST9AKDT,M3.2.0,M11.1.0"},
{"America/Yellowknife","MST7MDT,M3.2.0,M11.1.0"},
{"Antarctica/Casey","AWST-8"},
{"Antarctica/Davis","DAVT-7"},
{"Antarctica/DumontDUrville","DDUT-10"},
{"Antarctica/Macquarie","MIST-11"},
{"Antarctica/Mawson","MAWT-5"},
{"Antarctica/McMurdo","NZST-12NZDT,M9.5.0,M4.1.0/3"},
{"Antarctica/Palmer","CLT3"},
{"Antarctica/Rothera","ROTT3"},
{"Antarctica/South_Pole","NZST-12NZDT,M9.5.0,M4.1.0/3"},
{"Antarctica/Syowa","SYOT-3"},
{"Antarctica/Troll","UTC0CEST-2,M3.5.0/1,M10.5.0/3"},
{"Antarctica/Vostok","VOST-6"},
{"Arctic/Longyearbyen","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Asia/Aden","AST-3"},
{"Asia/Almaty","ALMT-6"},
{"Asia/Amman","EET-2EEST,M3.5.4/24,M10.5.5/1"},
{"Asia/Anadyr","ANAT-12"},
{"Asia/Aqtau","AQTT-5"},
{"Asia/Aqtobe","AQTT-5"},
{"Asia/Ashgabat","TMT-5"},
{"Asia/Ashkhabad","TMT-5"},
{"Asia/Baghdad","AST-3"},
{"Asia/Bahrain","AST-3"},
{"Asia/Baku","AZT-4AZST,M3.5.0/4,M10.5.0/5"},
{"Asia/Bangkok","ICT-7"},
{"Asia/Beirut","EET-2EEST,M3.5.0/0,M10.5.0/0"},
{"Asia/Bishkek","KGT-6"},
{"Asia/Brunei","BNT-8"},
{"Asia/Calcutta","IST-5:30"},
{"Asia/Chita","IRKT-8"},
{"Asia/Choibalsan","CHOT-8CHOST,M3.5.6,M9.5.6/0"},
{"Asia/Chongqing","CST-8"},
{"Asia/Chungking","CST-8"},
{"Asia/Colombo","IST-5:30"},
{"Asia/Dacca","BDT-6"},
{"Asia/Damascus","EET-2EEST,M3.5.5/0,M10.5.5/0"},
{"Asia/Dhaka","BDT-6"},
{"Asia/Dili","TLT-9"},
{"Asia/Dubai","GST-4"},
{"Asia/Dushanbe","TJT-5"},
{"Asia/Gaza","EET-2EEST,M3.5.5/24,M10.3.6/144"},
{"Asia/Harbin","CST-8"},
{"Asia/Hebron","EET-2EEST,M3.5.5/24,M10.3.6/144"},
{"Asia/Ho_Chi_Minh","ICT-7"},
{"Asia/Hong_Kong","HKT-8"},
{"Asia/Hovd","HOVT-7HOVST,M3.5.6,M9.5.6/0"},
{"Asia/Irkutsk","IRKT-8"},
{"Asia/Istanbul","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Asia/Jakarta","WIB-7"},
{"Asia/Jayapura","WIT-9"},
{"Asia/Jerusalem","IST-2IDT,M3.4.4/26,M10.5.0"},
{"Asia/Kabul","AFT-4:30"},
{"Asia/Kamchatka","PETT-12"},
{"Asia/Karachi","PKT-5"},
{"Asia/Kashgar","XJT-6"},
{"Asia/Kathmandu","NPT-5:45"},
{"Asia/Katmandu","NPT-5:45"},
{"Asia/Khandyga","YAKT-9"},
{"Asia/Kolkata","IST-5:30"},
{"Asia/Krasnoyarsk","KRAT-7"},
{"Asia/Kuala_Lumpur","MYT-8"},
{"Asia/Kuching","MYT-8"},
{"Asia/Kuwait","AST-3"},
{"Asia/Macao","CST-8"},
{"Asia/Macau","CST-8"},
{"Asia/Magadan","MAGT-10"},
{"Asia/Makassar","WITA-8"},
{"Asia/Manila","PHT-8"},
{"Asia/Muscat","GST-4"},
{"Asia/Nicosia","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Asia/Novokuznetsk","KRAT-7"},
{"Asia/Novosibirsk","NOVT-6"},
{"Asia/Omsk","OMST-6"},
{"Asia/Oral","ORAT-5"},
{"Asia/Phnom_Penh","ICT-7"},
{"Asia/Pontianak","WIB-7"},
{"Asia/Pyongyang","KST-8:30"},
{"Asia/Qatar","AST-3"},
{"Asia/Qyzylorda","QYZT-6"},
{"Asia/Rangoon","MMT-6:30"},
{"Asia/Riyadh","AST-3"},
{"Asia/Saigon","ICT-7"},
{"Asia/Sakhalin","SAKT-10"},
{"Asia/Samarkand","UZT-5"},
{"Asia/Seoul","KST-9"},
{"Asia/Shanghai","CST-8"},
{"Asia/Singapore","SGT-8"},
{"Asia/Srednekolymsk","SRET-11"},
{"Asia/Taipei","CST-8"},
{"Asia/Tashkent","UZT-5"},
{"Asia/Tbilisi","GET-4"},
{"Asia/Tehran","IRST-3:30IRDT,80/0,264/0"},
{"Asia/Tel_Aviv","IST-2IDT,M3.4.4/26,M10.5.0"},
{"Asia/Thimbu","BTT-6"},
{"Asia/Thimphu","BTT-6"},
{"Asia/Tokyo","JST-9"},
{"Asia/Ujung_Pandang","WITA-8"},
{"Asia/Ulaanbaatar","ULAT-8ULAST,M3.5.6,M9.5.6/0"},
{"Asia/Ulan_Bator","ULAT-8ULAST,M3.5.6,M9.5.6/0"},
{"Asia/Urumqi","XJT-6"},
{"Asia/Ust-Nera","VLAT-10"},
{"Asia/Vientiane","ICT-7"},
{"Asia/Vladivostok","VLAT-10"},
{"Asia/Yakutsk","YAKT-9"},
{"Asia/Yekaterinburg","YEKT-5"},
{"Asia/Yerevan","AMT-4"},
{"Atlantic/Azores","AZOT1AZOST,M3.5.0/0,M10.5.0/1"},
{"Atlantic/Bermuda","AST4ADT,M3.2.0,M11.1.0"},
{"Atlantic/Canary","WET0WEST,M3.5.0/1,M10.5.0"},
{"Atlantic/Cape_Verde","CVT1"},
{"Atlantic/Faeroe","WET0WEST,M3.5.0/1,M10.5.0"},
{"Atlantic/Faroe","WET0WEST,M3.5.0/1,M10.5.0"},
{"Atlantic/Jan_Mayen","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Atlantic/Madeira","WET0WEST,M3.5.0/1,M10.5.0"},
{"Atlantic/Reykjavik","GMT0"},
{"Atlantic/South_Georgia","GST2"},
{"Atlantic/Stanley","FKST3"},
{"Atlantic/St_Helena","GMT0"},
{"Australia/ACT","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Adelaide","ACST-9:30ACDT,M10.1.0,M4.1.0/3"},
{"Australia/Brisbane","AEST-10"},
{"Australia/Broken_Hill","ACST-9:30ACDT,M10.1.0,M4.1.0/3"},
{"Australia/Canberra","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Currie","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Darwin","ACST-9:30"},
{"Australia/Eucla","ACWST-8:45"},
{"Australia/Hobart","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/LHI","LHST-10:30LHDT-11,M10.1.0,M4.1.0"},
{"Australia/Lindeman","AEST-10"},
{"Australia/Lord_Howe","LHST-10:30LHDT-11,M10.1.0,M4.1.0"},
{"Australia/Melbourne","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/North","ACST-9:30"},
{"Australia/NSW","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Perth","AWST-8"},
{"Australia/Queensland","AEST-10"},
{"Australia/South","ACST-9:30ACDT,M10.1.0,M4.1.0/3"},
{"Australia/Sydney","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Tasmania","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/Victoria","AEST-10AEDT,M10.1.0,M4.1.0/3"},
{"Australia/West","AWST-8"},
{"Australia/Yancowinna","ACST-9:30ACDT,M10.1.0,M4.1.0/3"},
{"Europe/Amsterdam","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Andorra","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Athens","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Belfast","GMT0BST,M3.5.0/1,M10.5.0"},
{"Europe/Belgrade","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Berlin","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Bratislava","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Brussels","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Bucharest","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Budapest","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Busingen","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Chisinau","EET-2EEST,M3.5.0,M10.5.0/3"},
{"Europe/Copenhagen","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Dublin","GMT0IST,M3.5.0/1,M10.5.0"},
{"Europe/Gibraltar","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Guernsey","GMT0BST,M3.5.0/1,M10.5.0"},
{"Europe/Helsinki","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Isle_of_Man","GMT0BST,M3.5.0/1,M10.5.0"},
{"Europe/Istanbul","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Jersey","GMT0BST,M3.5.0/1,M10.5.0"},
{"Europe/Kaliningrad","EET-2"},
{"Europe/Kiev","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Kyiv","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Lisbon","WET0WEST,M3.5.0/1,M10.5.0"},
{"Europe/Ljubljana","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/London","GMT0BST,M3.5.0/1,M10.5.0"},
{"Europe/Luxembourg","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Madrid","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Malta","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Mariehamn","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Minsk","MSK-3"},
{"Europe/Monaco","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Moscow","MSK-3"},
{"Europe/Nicosia","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Oslo","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Paris","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Podgorica","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Prague","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Riga","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Rome","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Samara","SAMT-4"},
{"Europe/San_Marino","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Sarajevo","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Simferopol","MSK-3"},
{"Europe/Skopje","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Sofia","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Stockholm","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Tallinn","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Tirane","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Tiraspol","EET-2EEST,M3.5.0,M10.5.0/3"},
{"Europe/Vaduz","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Vatican","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Vienna","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Vilnius","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Europe/Volgograd","MSK-3"},
{"Europe/Warsaw","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Zagreb","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Europe/Zurich","CET-1CEST,M3.5.0,M10.5.0/3"},
{"Indian/Antananarivo","EAT-3"},
{"Indian/Chagos","IOT-6"},
{"Indian/Christmas","CXT-7"},
{"Indian/Cocos","CCT-6:30"},
{"Indian/Comoro","EAT-3"},
{"Indian/Kerguelen","TFT-5"},
{"Indian/Mahe","SCT-4"},
{"Indian/Maldives","MVT-5"},
{"Indian/Mauritius","MUT-4"},
{"Indian/Mayotte","EAT-3"},
{"Indian/Reunion","RET-4"},
{"Pacific/Apia","WSST-13WSDT,M9.5.0/3,M4.1.0/4"},
{"Pacific/Auckland","NZST-12NZDT,M9.5.0,M4.1.0/3"},
{"Pacific/Bougainville","BST-11"},
{"Pacific/Chatham","CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45"},
{"Pacific/Chuuk","CHUT-10"},
{"Pacific/Easter","EAST5"},
{"Pacific/Efate","VUT-11"},
{"Pacific/Kanton","PHOT-13"},
{"Pacific/Fakaofo","TKT-13"},
{"Pacific/Fiji","FJT-12FJST,M11.1.0,M1.3.0/3"},
{"Pacific/Funafuti","TVT-12"},
{"Pacific/Galapagos","GALT6"},
{"Pacific/Gambier","GAMT9"},
{"Pacific/Guadalcanal","SBT-11"},
{"Pacific/Guam","ChST-10"},
{"Pacific/Honolulu","HST10"},
{"Pacific/Johnston","HST10"},
{"Pacific/Kiritimati","LINT-14"},
{"Pacific/Kosrae","KOST-11"},
{"Pacific/Kwajalein","MHT-12"},
{"Pacific/Majuro","MHT-12"},
{"Pacific/Marquesas","MART9:30"},
{"Pacific/Midway","SST11"},
{"Pacific/Nauru","NRT-12"},
{"Pacific/Niue","NUT11"},
{"Pacific/Norfolk","NFT-11"},
{"Pacific/Noumea","NCT-11"},
{"Pacific/Pago_Pago","SST11"},
{"Pacific/Palau","PWT-9"},
{"Pacific/Pitcairn","PST8"},
{"Pacific/Pohnpei","PONT-11"},
{"Pacific/Ponape","PONT-11"},
{"Pacific/Port_Moresby","PGT-10"},
{"Pacific/Rarotonga","CKT10"},
{"Pacific/Saipan","ChST-10"},
{"Pacific/Samoa","SST11"},
{"Pacific/Tahiti","TAHT10"},
{"Pacific/Tarawa","GILT-12"},
{"Pacific/Tongatapu","TOT-13"},
{"Pacific/Truk","CHUT-10"},
{"Pacific/Wake","WAKT-12"},
{"Pacific/Wallis","WFT-12"},
{"Pacific/Yap","CHUT-10"},
{"Etc/UTC","UTC0"},
{"America/Halifax","AST4ADT,M3.2.0,M11.1.0"},
{"America/Indiana/Knox","CST6CDT,M3.2.0,M11.1.0"},
{"America/Phoenix","MST7"},
{"America/Punta_Arenas","UNK3"},
{"Asia/Atyrau","UNK-5"},
{"Asia/Barnaul","UNK-7"},
{"Asia/Famagusta","EET-2EEST,M3.5.0/3,M10.5.0/4"},
{"Asia/Tomsk","UNK-7"},
{"Asia/Yangon","UNK-6:30"},
{"Europe/Astrakhan","UNK-4"},
{"Europe/Kirov","UNK-3"},
{"Europe/Saratov","UNK-4"},
{"Europe/Ulyanovsk","UNK-4"},
{"Asia/Qostanay","ALMT-6"},
{"America/Nuuk","WGT3WGST,M3.5.0/-2,M10.5.0/-1"},

};

*/


const char* timezone_dropdown_options = ""
"Africa/Abidjan\n"
"Africa/Accra\n"
"Africa/Addis_Ababa\n"
"Africa/Algiers\n"
"Africa/Asmara\n"
"Africa/Asmera\n"
"Africa/Bamako\n"
"Africa/Bangui\n"
"Africa/Banjul\n"
"Africa/Bissau\n"
"Africa/Blantyre\n"
"Africa/Brazzaville\n"
"Africa/Bujumbura\n"
"Africa/Cairo\n"
"Africa/Casablanca\n"
"Africa/Ceuta\n"
"Africa/Conakry\n"
"Africa/Dakar\n"
"Africa/Dar_es_Salaam\n"
"Africa/Djibouti\n"
"Africa/Douala\n"
"Africa/El_Aaiun\n"
"Africa/Freetown\n"
"Africa/Gaborone\n"
"Africa/Harare\n"
"Africa/Johannesburg\n"
"Africa/Juba\n"
"Africa/Kampala\n"
"Africa/Khartoum\n"
"Africa/Kigali\n"
"Africa/Kinshasa\n"
"Africa/Lagos\n"
"Africa/Libreville\n"
"Africa/Lome\n"
"Africa/Luanda\n"
"Africa/Lubumbashi\n"
"Africa/Lusaka\n"
"Africa/Malabo\n"
"Africa/Maputo\n"
"Africa/Maseru\n"
"Africa/Mbabane\n"
"Africa/Mogadishu\n"
"Africa/Monrovia\n"
"Africa/Nairobi\n"
"Africa/Ndjamena\n"
"Africa/Niamey\n"
"Africa/Nouakchott\n"
"Africa/Ouagadougou\n"
"Africa/Porto-Novo\n"
"Africa/Sao_Tome\n"
"Africa/Timbuktu\n"
"Africa/Tripoli\n"
"Africa/Tunis\n"
"Africa/Windhoek\n"
"America/Adak\n"
"America/Anchorage\n"
"America/Anguilla\n"
"America/Antigua\n"
"America/Araguaina\n"
"America/Argentina/Buenos_Aires\n"
"America/Argentina/Catamarca\n"
"America/Argentina/ComodRivadavia\n"
"America/Argentina/Cordoba\n"
"America/Argentina/Jujuy\n"
"America/Argentina/La_Rioja\n"
"America/Argentina/Mendoza\n"
"America/Argentina/Rio_Gallegos\n"
"America/Argentina/Salta\n"
"America/Argentina/San_Juan\n"
"America/Argentina/San_Luis\n"
"America/Argentina/Tucuman\n"
"America/Argentina/Ushuaia\n"
"America/Aruba\n"
"America/Asuncion\n"
"America/Atikokan\n"
"America/Atka\n"
"America/Bahia\n"
"America/Bahia_Banderas\n"
"America/Barbados\n"
"America/Belem\n"
"America/Belize\n"
"America/Blanc-Sablon\n"
"America/Boa_Vista\n"
"America/Bogota\n"
"America/Boise\n"
"America/Buenos_Aires\n"
"America/Cambridge_Bay\n"
"America/Campo_Grande\n"
"America/Cancun\n"
"America/Caracas\n"
"America/Catamarca\n"
"America/Cayenne\n"
"America/Cayman\n"
"America/Chicago\n"
"America/Chihuahua\n"
"America/Ciudad_Juarez\n"
"America/Coral_Harbour\n"
"America/Cordoba\n"
"America/Costa_Rica\n"
"America/Creston\n"
"America/Cuiaba\n"
"America/Curacao\n"
"America/Danmarkshavn\n"
"America/Dawson\n"
"America/Dawson_Creek\n"
"America/Denver\n"
"America/Detroit\n"
"America/Dominica\n"
"America/Edmonton\n"
"America/Eirunepe\n"
"America/El_Salvador\n"
"America/Ensenada\n"
"America/Fortaleza\n"
"America/Fort_Nelson\n"
"America/Fort_Wayne\n"
"America/Glace_Bay\n"
"America/Goose_Bay\n"
"America/Grand_Turk\n"
"America/Grenada\n"
"America/Guadeloupe\n"
"America/Guatemala\n"
"America/Guayaquil\n"
"America/Guyana\n"
"America/Halifa\n"
"America/Havana\n"
"America/Hermosillo\n"
"America/Indiana/Indianapolis\n"
"America/Indiana/Kno\n"
"America/Indiana/Marengo\n"
"America/Indiana/Petersburg\n"
"America/Indianapolis\n"
"America/Indiana/Tell_City\n"
"America/Indiana/Vevay\n"
"America/Indiana/Vincennes\n"
"America/Indiana/Winamac\n"
"America/Inuvik\n"
"America/Iqaluit\n"
"America/Jamaica\n"
"America/Jujuy\n"
"America/Juneau\n"
"America/Kentucky/Louisville\n"
"America/Kentucky/Monticello\n"
"America/Knox_IN\n"
"America/Kralendijk\n"
"America/La_Paz\n"
"America/Lima\n"
"America/Los_Angeles\n"
"America/Louisville\n"
"America/Lower_Princes\n"
"America/Maceio\n"
"America/Managua\n"
"America/Manaus\n"
"America/Marigot\n"
"America/Martinique\n"
"America/Matamoros\n"
"America/Mazatlan\n"
"America/Mendoza\n"
"America/Menominee\n"
"America/Merida\n"
"America/Metlakatla\n"
"America/Mexico_City\n"
"America/Miquelon\n"
"America/Moncton\n"
"America/Monterrey\n"
"America/Montevideo\n"
"America/Montreal\n"
"America/Montserrat\n"
"America/Nassau\n"
"America/New_York\n"
"America/Nipigon\n"
"America/Nome\n"
"America/Noronha\n"
"America/North_Dakota/Beulah\n"
"America/North_Dakota/Center\n"
"America/North_Dakota/New_Salem\n"
"America/Ojinaga\n"
"America/Panama\n"
"America/Pangnirtung\n"
"America/Paramaribo\n"
"America/Phoeni\n"
"America/Port-au-Prince\n"
"America/Porto_Acre\n"
"America/Port_of_Spain\n"
"America/Porto_Velho\n"
"America/Puerto_Rico\n"
"America/Rainy_River\n"
"America/Rankin_Inlet\n"
"America/Recife\n"
"America/Regina\n"
"America/Resolute\n"
"America/Rio_Branco\n"
"America/Rosario\n"
"America/Santa_Isabel\n"
"America/Santarem\n"
"America/Santiago\n"
"America/Santo_Domingo\n"
"America/Sao_Paulo\n"
"America/Scoresbysund\n"
"America/Shiprock\n"
"America/Sitka\n"
"America/St_Barthelemy\n"
"America/St_Johns\n"
"America/St_Kitts\n"
"America/St_Lucia\n"
"America/St_Thomas\n"
"America/St_Vincent\n"
"America/Swift_Current\n"
"America/Tegucigalpa\n"
"America/Thule\n"
"America/Thunder_Bay\n"
"America/Tijuana\n"
"America/Toronto\n"
"America/Tortola\n"
"America/Vancouver\n"
"America/Virgin\n"
"America/Whitehorse\n"
"America/Winnipeg\n"
"America/Yakutat\n"
"America/Yellowknife\n"
"Antarctica/Casey\n"
"Antarctica/Davis\n"
"Antarctica/DumontDUrville\n"
"Antarctica/Macquarie\n"
"Antarctica/Mawson\n"
"Antarctica/McMurdo\n"
"Antarctica/Palmer\n"
"Antarctica/Rothera\n"
"Antarctica/South_Pole\n"
"Antarctica/Syowa\n"
"Antarctica/Troll\n"
"Antarctica/Vostok\n"
"Arctic/Longyearbyen\n"
"Asia/Aden\n"
"Asia/Almaty\n"
"Asia/Amman\n"
"Asia/Anadyr\n"
"Asia/Aqtau\n"
"Asia/Aqtobe\n"
"Asia/Ashgabat\n"
"Asia/Ashkhabad\n"
"Asia/Baghdad\n"
"Asia/Bahrain\n"
"Asia/Baku\n"
"Asia/Bangkok\n"
"Asia/Beirut\n"
"Asia/Bishkek\n"
"Asia/Brunei\n"
"Asia/Calcutta\n"
"Asia/Chita\n"
"Asia/Choibalsan\n"
"Asia/Chongqing\n"
"Asia/Chungking\n"
"Asia/Colombo\n"
"Asia/Dacca\n"
"Asia/Damascus\n"
"Asia/Dhaka\n"
"Asia/Dili\n"
"Asia/Dubai\n"
"Asia/Dushanbe\n"
"Asia/Gaza\n"
"Asia/Harbin\n"
"Asia/Hebron\n"
"Asia/Ho_Chi_Minh\n"
"Asia/Hong_Kong\n"
"Asia/Hovd\n"
"Asia/Irkutsk\n"
"Asia/Istanbul\n"
"Asia/Jakarta\n"
"Asia/Jayapura\n"
"Asia/Jerusalem\n"
"Asia/Kabul\n"
"Asia/Kamchatka\n"
"Asia/Karachi\n"
"Asia/Kashgar\n"
"Asia/Kathmandu\n"
"Asia/Katmandu\n"
"Asia/Khandyga\n"
"Asia/Kolkata\n"
"Asia/Krasnoyarsk\n"
"Asia/Kuala_Lumpur\n"
"Asia/Kuching\n"
"Asia/Kuwait\n"
"Asia/Macao\n"
"Asia/Macau\n"
"Asia/Magadan\n"
"Asia/Makassar\n"
"Asia/Manila\n"
"Asia/Muscat\n"
"Asia/Nicosia\n"
"Asia/Novokuznetsk\n"
"Asia/Novosibirsk\n"
"Asia/Omsk\n"
"Asia/Oral\n"
"Asia/Phnom_Penh\n"
"Asia/Pontianak\n"
"Asia/Pyongyang\n"
"Asia/Qatar\n"
"Asia/Qyzylorda\n"
"Asia/Rangoon\n"
"Asia/Riyadh\n"
"Asia/Saigon\n"
"Asia/Sakhalin\n"
"Asia/Samarkand\n"
"Asia/Seoul\n"
"Asia/Shanghai\n"
"Asia/Singapore\n"
"Asia/Srednekolymsk\n"
"Asia/Taipei\n"
"Asia/Tashkent\n"
"Asia/Tbilisi\n"
"Asia/Tehran\n"
"Asia/Tel_Aviv\n"
"Asia/Thimbu\n"
"Asia/Thimphu\n"
"Asia/Tokyo\n"
"Asia/Ujung_Pandang\n"
"Asia/Ulaanbaatar\n"
"Asia/Ulan_Bator\n"
"Asia/Urumqi\n"
"Asia/Ust-Nera\n"
"Asia/Vientiane\n"
"Asia/Vladivostok\n"
"Asia/Yakutsk\n"
"Asia/Yekaterinburg\n"
"Asia/Yerevan\n"
"Atlantic/Azores\n"
"Atlantic/Bermuda\n"
"Atlantic/Canary\n"
"Atlantic/Cape_Verde\n"
"Atlantic/Faeroe\n"
"Atlantic/Faroe\n"
"Atlantic/Jan_Mayen\n"
"Atlantic/Madeira\n"
"Atlantic/Reykjavik\n"
"Atlantic/South_Georgia\n"
"Atlantic/Stanley\n"
"Atlantic/St_Helena\n"
"Australia/ACT\n"
"Australia/Adelaide\n"
"Australia/Brisbane\n"
"Australia/Broken_Hill\n"
"Australia/Canberra\n"
"Australia/Currie\n"
"Australia/Darwin\n"
"Australia/Eucla\n"
"Australia/Hobart\n"
"Australia/LHI\n"
"Australia/Lindeman\n"
"Australia/Lord_Howe\n"
"Australia/Melbourne\n"
"Australia/North\n"
"Australia/NSW\n"
"Australia/Perth\n"
"Australia/Queensland\n"
"Australia/South\n"
"Australia/Sydney\n"
"Australia/Tasmania\n"
"Australia/Victoria\n"
"Australia/West\n"
"Australia/Yancowinna\n"
"Europe/Amsterdam\n"
"Europe/Andorra\n"
"Europe/Athens\n"
"Europe/Belfast\n"
"Europe/Belgrade\n"
"Europe/Berlin\n"
"Europe/Bratislava\n"
"Europe/Brussels\n"
"Europe/Bucharest\n"
"Europe/Budapest\n"
"Europe/Busingen\n"
"Europe/Chisinau\n"
"Europe/Copenhagen\n"
"Europe/Dublin\n"
"Europe/Gibraltar\n"
"Europe/Guernsey\n"
"Europe/Helsinki\n"
"Europe/Isle_of_Man\n"
"Europe/Istanbul\n"
"Europe/Jersey\n"
"Europe/Kaliningrad\n"
"Europe/Kiev\n"
"Europe/Kyiv\n"
"Europe/Lisbon\n"
"Europe/Ljubljana\n"
"Europe/London\n"
"Europe/Luxembourg\n"
"Europe/Madrid\n"
"Europe/Malta\n"
"Europe/Mariehamn\n"
"Europe/Minsk\n"
"Europe/Monaco\n"
"Europe/Moscow\n"
"Europe/Nicosia\n"
"Europe/Oslo\n"
"Europe/Paris\n"
"Europe/Podgorica\n"
"Europe/Prague\n"
"Europe/Riga\n"
"Europe/Rome\n"
"Europe/Samara\n"
"Europe/San_Marino\n"
"Europe/Sarajevo\n"
"Europe/Simferopol\n"
"Europe/Skopje\n"
"Europe/Sofia\n"
"Europe/Stockholm\n"
"Europe/Tallinn\n"
"Europe/Tirane\n"
"Europe/Tiraspol\n"
"Europe/Vaduz\n"
"Europe/Vatican\n"
"Europe/Vienna\n"
"Europe/Vilnius\n"
"Europe/Volgograd\n"
"Europe/Warsaw\n"
"Europe/Zagreb\n"
"Europe/Zurich\n"
"Indian/Antananarivo\n"
"Indian/Chagos\n"
"Indian/Christmas\n"
"Indian/Cocos\n"
"Indian/Comoro\n"
"Indian/Kerguelen\n"
"Indian/Mahe\n"
"Indian/Maldives\n"
"Indian/Mauritius\n"
"Indian/Mayotte\n"
"Indian/Reunion\n"
"Pacific/Apia\n"
"Pacific/Auckland\n"
"Pacific/Bougainville\n"
"Pacific/Chatham\n"
"Pacific/Chuuk\n"
"Pacific/Easter\n"
"Pacific/Efate\n"
"Pacific/Kanton\n"
"Pacific/Fakaofo\n"
"Pacific/Fiji\n"
"Pacific/Funafuti\n"
"Pacific/Galapagos\n"
"Pacific/Gambier\n"
"Pacific/Guadalcanal\n"
"Pacific/Guam\n"
"Pacific/Honolulu\n"
"Pacific/Johnston\n"
"Pacific/Kiritimati\n"
"Pacific/Kosrae\n"
"Pacific/Kwajalein\n"
"Pacific/Majuro\n"
"Pacific/Marquesas\n"
"Pacific/Midway\n"
"Pacific/Nauru\n"
"Pacific/Niue\n"
"Pacific/Norfolk\n"
"Pacific/Noumea\n"
"Pacific/Pago_Pago\n"
"Pacific/Palau\n"
"Pacific/Pitcairn\n"
"Pacific/Pohnpei\n"
"Pacific/Ponape\n"
"Pacific/Port_Moresby\n"
"Pacific/Rarotonga\n"
"Pacific/Saipan\n"
"Pacific/Samoa\n"
"Pacific/Tahiti\n"
"Pacific/Tarawa\n"
"Pacific/Tongatapu\n"
"Pacific/Truk\n"
"Pacific/Wake\n"
"Pacific/Wallis\n"
"Pacific/Yap\n"
"Etc/UTC\n"
"America/Halifax\n"
"America/Indiana/Knox\n"
"America/Phoenix\n"
"America/Punta_Arenas\n"
"Asia/Atyrau\n"
"Asia/Barnaul\n"
"Asia/Famagusta\n"
"Asia/Tomsk\n"
"Asia/Yangon\n"
"Europe/Astrakhan\n"
"Europe/Kirov\n"
"Europe/Saratov\n"
"Europe/Ulyanovsk\n"
"Asia/Qostanay\n"
"America/Nuuk\n"
;